### ISSUE TITLE
Strange behaviour with sysv

### ISSUE THREAD

**Issue by james-portman** [evrardjp/ansible-keepalived#57] opened 2018-01-25 12:59 UTC
Hi,

Just starting this so I don't forget.
I am using a fork of the repo with systemd rather than sysv which gives more predictable behaviour,
just wondered your thoughts on this.
Maybe it is something to take up with keepalived devs, or I might have missed something also.

Example service file:
```
[Unit]
Description=Keepalived
After=network.target

[Service]
Type=simple
ExecStart=/usr/sbin/keepalived --log-console --dont-fork -f /etc/keepalived/keepalived.conf
ExecStop=/usr/bin/pkill keepalived
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Comment by evrardjp** [comment] 2018-02-12 10:44
I think the ppa is using systemd by default now.

I am not sure what the problem is, except "Strange behaviour"  :)

Could you be more explicit, please?

**Comment by james-portman** [comment] 2018-02-12 10:46
Hi,
I will double check but I thought it was using sysv still.
Basically the strange behaviour is that (as with most services doing this) - if systemd starts a sysv script, it just returns as successful even if it completely failed.
It also had some trouble restarting.

I'll go and check if I was using PPA and retest it for more info...

**Comment by evrardjp** [comment] 2018-11-11 17:00
I am closing this, as it's been pending for a while. Thanks for having a look :)

**Closed by evrardjp** 2018-11-11 17:00 UTC
